<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class CategoriasResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        // return parent::toArray($request);
        return  [
            'id' => $this->id,
            'nombre' => $this->nombre,
        ];
    }

    public  function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return  [
            'res' => true
        ];
    }
}
