<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class SedeResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        //return parent::toArray($request);

        return  [
            'id' => $this->id,
            'nombre' => $this->nombre,
            'eliminado' => $this->eliminado,
            'institucion_id' => $this->institucion_id,
            'municipio_id' => $this->municipio_id
        ];
    }

    public  function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return [
            'res' => true
        ];
    }
}
